package com.stone.movieticket.utils

const val BASE_URL = "https://tmba.padc.com.mm"
const val BASE_IMG_URL="https://image.tmdb.org/t/p/original"
const val BASE_PROFILE_URL="https://tmba.padc.com.mm"
//const val IMAGE_BASE_URL="https://image.tmdb.org/t/p/w400"
const val API_GET_NOW_SHOWING="/api/v1/movies"
const val API_REGISTER = "/api/v1/register"
const val API_LOGIN = "/api/v1/email-login"
const val API_PROFILE="/api/v1/profile"
const val API_LOGOUT="/api/v1/logout"
const val API_MOVIE_DETAIL="/api/v1/movies"
const val API_CINEMA_TIME_SLOT="/api/v1/cinema-day-timeslots"
const val API_MOVIE_SEAT="/api/v1/seat-plan"
const val API_SNACK="/api/v1/snacks"
const val API_PAYMENT="/api/v1/payment-methods"
const val API_CARD="/api/v1/card"
const val API_CHECKOUT="/api/v1/checkout"

const val PARAM_STATUS="status"
const val PARAM_NAME="name"
const val PARAM_AUTHORIZATION="AUTHORIZATION"
const val PARAM_EMAIL="email"
const val PARAM_PASSWORD="password"
const val PARAM_PHONE="phone"
const val PARAM_DATE="date"
const val PARAM_MOVIE_ID="movie_id"
const val PARAM_CINEMA_TIMESLOT_ID="cinema_day_timeslot_id"
const val PARAM_BOOKING_DATE="booking_date"
const val PARAM_CARD_NUMBER="card_number"
const val PARAM_CARD_HOLDER="card_holder"
const val PARAM_EXPIRATION_DATE="expiration_date"
const val PARAM_CVC="cvc"