package com.stone.movieticket.utils

import com.stone.movieticket.data.vos.*

//val DUMMY_SEAT_LIST = listOf(
//    MovieSeatVO(title = "A", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "", type = SEAT_TYPE_EMPTY),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_EMPTY),
//    MovieSeatVO(title = "A", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "B", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "B", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "C", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_TOKEN),
//    MovieSeatVO(title = "", type = SEAT_TYPE_TOKEN),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "C", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "D", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_TOKEN),
//    MovieSeatVO(title = "", type = SEAT_TYPE_TOKEN),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "D", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "E", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "", type = SEAT_TYPE_TOKEN),
//    MovieSeatVO(title = "", type = SEAT_TYPE_TOKEN),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "E", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "F", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "F", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "G", type = SEAT_TYPE_TEXT),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "", type = SEAT_TYPE_AVAILABLE),
//    MovieSeatVO(title = "G", type = SEAT_TYPE_TEXT),
//
//
//)